In [1]:
import re
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/harshraj/Desktop/NLP/questions.csv')
df

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0
...,...,...,...,...,...,...
404346,404346,789792,789793,How many keywords are there in the Racket prog...,How many keywords are there in PERL Programmin...,0
404347,404347,789794,789795,Do you believe there is life after death?,Is it true that there is life after death?,1
404348,404348,789796,789797,What is one coin?,What's this coin?,0
404349,404349,789798,789799,What is the approx annual cost of living while...,I am having little hairfall problem but I want...,0
404350,404350,789800,789801,What is like to have sex with cousin?,What is it like to have sex with your cousin?,0

In [3]:
df.isnull().sum()

id              0
qid1            0
qid2            0
question1       1
question2       2
is_duplicate    0
dtype: int64

In [4]:
df = df.dropna()

In [5]:
df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [8]:
df['question1'] = df['question1'].str.lower()
df['question2'] = df['question2'].str.lower()

In [9]:
def remove_tags(text):
    cleaned = re.sub(r'<.*?>', '', text)
    return cleaned

In [10]:
df['question1'] = df['question1'].apply(remove_tags)
df['question2'] = df['question2'].apply(remove_tags)

In [11]:
df

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,what is the step by step guide to invest in sh...,what is the step by step guide to invest in sh...,0
1,1,3,4,what is the story of kohinoor (koh-i-noor) dia...,what would happen if the indian government sto...,0
2,2,5,6,how can i increase the speed of my internet co...,how can internet speed be increased by hacking...,0
3,3,7,8,why am i mentally very lonely? how can i solve...,find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"which one dissolve in water quikly sugar, salt...",which fish would survive in salt water?,0
...,...,...,...,...,...,...
404346,404346,789792,789793,how many keywords are there in the racket prog...,how many keywords are there in perl programmin...,0
404347,404347,789794,789795,do you believe there is life after death?,is it true that there is life after death?,1
404348,404348,789796,789797,what is one coin?,what's this coin?,0
404349,404349,789798,789799,what is the approx annual cost of living while...,i am having little hairfall problem but i want...,0
404350,404350,789800,789801,what is like to have sex with cousin?,what is it like to have sex with your cousin?,0

In [12]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)
df['question1'] = df['question1'].apply(remove_url)
df['question2'] = df['question2'].apply(remove_url)

In [18]:
import string,time
exclusion = string.punctuation
def remove_punc1(text):
    return text.translate(str.maketrans('', '', exclusion))


df['question1'] = df['question1'].apply(remove_punc1)
df['question2'] = df['question2'].apply(remove_punc1)

In [ ]:
from textblob import TextBlob

def spell_check(text):
    return str(TextBlob(text).correct()) 
df['question1'] = df['question1'].apply(spell_check)
df['question2'] = df['question2'].apply(spell_check)

In [ ]:
!pip install emoji

'astrology i am a capricorn sun cap moon and cap risingwhat does that say about me'

In [ ]:
df['question1'] = df['question1'].apply(emoji.demojize())
df['question2'] = df['question2'].apply(emoji.demojize())