In [10]:
!source .venv/bin/activate
!kaggle auth login
!kaggle datasets download -d lakshmi25npathi/imdb-dataset-of-50k-movie-reviews -p data/imdb --unzip

Your browser has been opened to visit:
  https://www.kaggle.com/api/v1/oauth2/authorize?response_type=code&client_id=kagglesdk&redirect_uri=http%3A%2F%2Flocalhost%3A8040&scope=resources.admin%3A%2A&state=a209ce3c-a80a-455c-ab3d-81153472c99e&code_challenge=3BR2MtiZ6h_pixygl24eN0Adr5W_8q-3qofNRib3xUo%3D&code_challenge_method=S256&response_mode=query


127.0.0.1 - - [28/May/2026 12:55:38] "GET /?code=CfDJ8G82xNY93phHtA6xMwIf8xOd4SSDKVDxJ5ZheJSq4ybQuBGNI4cu8kjSmieCVSZHWZZU6OSHplxH-cZT5BgZftIJbezII-l96Qiuq0sPF00a9EniseK4QnO_w2wooElVkZe6fDCeuZdLLE41GwW0Bm0ySRHQAhvBpsXYyuSSbXn6mdi7DzKFtpeZFLY1tpWmzlE1HGPxQVBpP8E7g7m5-1XGrCi1f3lNwR1v2UIyhaYbzjXAWfWLMuFH5GVw1prQY4YkZFc0xbba9DpmjLExeg9DTZ5ij_cujHn7gahKHf7XWQtic8IzTciTXsl0BA&state=a209ce3c-a80a-455c-ab3d-81153472c99e HTTP/1.1" 200 -

You are now logged in as [harshraj3112007]

Dataset URL: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
License(s): other
Downloading imdb-dataset-of-50k-movie-reviews.zip to data/imdb
100%|███████████████████████████████████████| 25.7M/25.7M [00:39<00:00, 685kB/s]

In [11]:
import pandas as pd
df = pd.read_csv("data/imdb/IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

# Lowercasing

In [13]:
# Assuming 'df' is your Pandas DataFrame and 'review' is the text column
df['review'] = df['review'].str.lower()

In [14]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# Removing HTML tags

In [15]:
import re

def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

# Applying it to a DataFrame column
df['review'] = df['review'].apply(remove_html_tags)

In [16]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# Removing URLs

In [17]:
import re

def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

# Applying it to a text
sample_text = "Check out this link: https://example.com"
clean_text = remove_url(sample_text)

In [19]:
df['review'] = df['review'].apply(remove_url)

In [20]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# Removing Punctuations - M1

In [22]:
import string,time
exclusion = string.punctuation

In [27]:
def remove_punc(text):
    for char in exclusion:
        text = text.replace(char,'')
    return text

text = 'string. With. Punctuation?'
clean_text = remove_punc(text)
print(clean_text)

string With Punctuation

In [25]:
df['review'] = df['review'].apply(remove_punc)

In [26]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# Removing Punctuations - M2

In [29]:
def remove_punc1(text):
    return text.translate(str.maketrans('', '', exclusion))

text = 'string. With. Punctuation?'
clean_text = remove_punc(text)
print(clean_text)

string With Punctuation

# Fixing Chat Words

In [ ]:
chat_words = {
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "BRB": "Be Right Back",
    "GN": "Good Night"
}

def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

text = "AFAIK ,I'll BRB after this meeting. GN ! "
clean_text = chat_conversion(text)
print(clean_text)

As Far As I Know , I'll Be Right Back after this meeting. Good Night !

In [45]:
df['review'] = df['review'].apply(chat_conversion)

In [47]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# Spell Correction

In [49]:
from textblob import TextBlob

def spell_check(text):
    return str(TextBlob(text).correct())

In [51]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# Stop Words Removal

In [52]:
from nltk.corpus import stopwords
import nltk

nltk.download('stopwords')
stop_words = stopwords.words('english')

def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word not in stop_words:
            new_text.append(word)
    return " ".join(new_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/harshraj/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [53]:
df['review'] = df['review'].apply(remove_stopwords)

In [54]:
df

                                                  review sentiment
0      one reviewers mentioned watching 1 oz episode ...  positive
1      wonderful little production filming technique ...  positive
2      thought wonderful way spend time hot summer we...  positive
3      basically theres family little boy jake thinks...  negative
4      petter matteis love time money visually stunni...  positive
...                                                  ...       ...
49995  thought movie right good job wasnt creative or...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  catholic taught parochial elementary schools n...  negative
49998  im going disagree previous comment side maltin...  negative
49999  one expects star trek movies high art fans exp...  negative

[50000 rows x 2 columns]

# Handling Emojis

In [55]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 392.8 kB/s  0:00:01eta 0:00:01
Installing collected packages: emoji
Successfully installed emoji-2.15.0

[notice] A new release of pip is available: 26.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [57]:
import emoji

text_with_emoji = "Python is 🔥"
converted_text = emoji.demojize(text_with_emoji)
print(converted_text)

Python is :fire:

In [65]:
import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [66]:
print(remove_emoji("Loved the movie. It was 😘😘"))

Loved the movie. It was

# Tokenisation

## Using NLTK

In [58]:
from nltk.tokenize import sent_tokenize, word_tokenize
import nltk

# Downloading the required NLTK data files (punkt)
nltk.download('punkt')

dummy_text = "This is a dummy text. It contains multiple sentences for tokenization."

# 1. Sentence Tokenization (Splits the paragraph into a list of sentences)
sentences = sent_tokenize(dummy_text)
print("Sentences:", sentences)

# 2. Word Tokenization (Splits the sentences into individual words)
for sentence in sentences:
    words = word_tokenize(sentence)
    print("Words:", words)

Sentences: ['This is a dummy text.', 'It contains multiple sentences for tokenization.']
Words: ['This', 'is', 'a', 'dummy', 'text', '.']
Words: ['It', 'contains', 'multiple', 'sentences', 'for', 'tokenization', '.']

[nltk_data] Downloading package punkt to /Users/harshraj/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

## Using spaCy

In [59]:
import spacy

# Load the English dictionary
nlp = spacy.load("en_core_web_sm")

text = "I have a Ph.D. in A.I. and I live in N.Y.C."
doc = nlp(text)

# Extracting tokens
for token in doc:
    print(token.text)

I
have
a
Ph.D.
in
A.I.
and
I
live
in
N.Y.C.

## Can be done with .split() fxn also but is not reproducible

In [67]:
# word tokenization
sent1 = 'I am going to delhi'
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [68]:
# sentence tokenization
sent2 = 'I am going to delhi. I will stay there for 3 days. Let\'s hope the trip to be great'
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

## Using Regular Expression

In [69]:
import re
sent3 = 'I am going to delhi!'
tokens = re.findall("[\w']+", sent3)
tokens

['I', 'am', 'going', 'to', 'delhi']

In [70]:

text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry? 
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""
sentences = re.compile('[.!?] ').split(text)
sentences

['Lorem Ipsum is simply dummy text of the printing and typesetting industry',
 "\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s, \nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

# Stemming

In [60]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [ ]:
df['review'] = df['review'].apply(stem_words)

In [62]:
df['review']

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production filming technique ...
2        thought wonderful way spend time hot summer we...
3        basically theres family little boy jake thinks...
4        petter matteis love time money visually stunni...
                               ...
49995    thought movie right good job wasnt creative or...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    catholic taught parochial elementary schools n...
49998    im going disagree previous comment side maltin...
49999    one expects star trek movies high art fans exp...
Name: review, Length: 50000, dtype: str

# Lemmatization

In [64]:
import nltk
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')
wordnet_lemmatizer = WordNetLemmatizer()

# You must specify the part of speech (pos="v" means verb)
word = "running"
lemma = wordnet_lemmatizer.lemmatize(word, pos="v")
print(lemma)

run

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/harshraj/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!